# ty has built-in LSP
ARG VERSION=latest
FROM ghcr.io/astral-sh/uv:python3.11-trixie-slim AS builder
ARG VERSION
RUN uv tool install ty@${VERSION}

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /usr/local/bin/ty /usr/local/bin/ty

WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/ty", "server"]
